// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response_error.proto

#ifndef PROTOBUF_response_5ferror_2eproto__INCLUDED
#define PROTOBUF_response_5ferror_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace happy {
namespace utils {
namespace network {
class ResponseError;
class ResponseErrorDefaultTypeInternal;
extern ResponseErrorDefaultTypeInternal _ResponseError_default_instance_;
}  // namespace network
}  // namespace utils
}  // namespace happy

namespace happy {
namespace utils {
namespace network {

namespace protobuf_response_5ferror_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_response_5ferror_2eproto

// ===================================================================

class ResponseError : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:happy.utils.network.ResponseError) */ {
 public:
  ResponseError();
  virtual ~ResponseError();

  ResponseError(const ResponseError& from);

  inline ResponseError& operator=(const ResponseError& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseError& default_instance();

  static inline const ResponseError* internal_default_instance() {
    return reinterpret_cast<const ResponseError*>(
               &_ResponseError_default_instance_);
  }

  void Swap(ResponseError* other);

  // implements Message ----------------------------------------------

  inline ResponseError* New() const PROTOBUF_FINAL { return New(NULL); }

  ResponseError* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResponseError& from);
  void MergeFrom(const ResponseError& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResponseError* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string error_string = 2;
  bool has_error_string() const;
  void clear_error_string();
  static const int kErrorStringFieldNumber = 2;
  const ::std::string& error_string() const;
  void set_error_string(const ::std::string& value);
  #if LANG_CXX11
  void set_error_string(::std::string&& value);
  #endif
  void set_error_string(const char* value);
  void set_error_string(const char* value, size_t size);
  ::std::string* mutable_error_string();
  ::std::string* release_error_string();
  void set_allocated_error_string(::std::string* error_string);

  // required int32 error_code = 1;
  bool has_error_code() const;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:happy.utils.network.ResponseError)
 private:
  void set_has_error_code();
  void clear_has_error_code();
  void set_has_error_string();
  void clear_has_error_string();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr error_string_;
  ::google::protobuf::int32 error_code_;
  friend struct  protobuf_response_5ferror_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ResponseError

// required int32 error_code = 1;
inline bool ResponseError::has_error_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseError::set_has_error_code() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseError::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseError::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 ResponseError::error_code() const {
  // @@protoc_insertion_point(field_get:happy.utils.network.ResponseError.error_code)
  return error_code_;
}
inline void ResponseError::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
  // @@protoc_insertion_point(field_set:happy.utils.network.ResponseError.error_code)
}

// required string error_string = 2;
inline bool ResponseError::has_error_string() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseError::set_has_error_string() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseError::clear_has_error_string() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseError::clear_error_string() {
  error_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_error_string();
}
inline const ::std::string& ResponseError::error_string() const {
  // @@protoc_insertion_point(field_get:happy.utils.network.ResponseError.error_string)
  return error_string_.GetNoArena();
}
inline void ResponseError::set_error_string(const ::std::string& value) {
  set_has_error_string();
  error_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:happy.utils.network.ResponseError.error_string)
}
#if LANG_CXX11
inline void ResponseError::set_error_string(::std::string&& value) {
  set_has_error_string();
  error_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:happy.utils.network.ResponseError.error_string)
}
#endif
inline void ResponseError::set_error_string(const char* value) {
  set_has_error_string();
  error_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:happy.utils.network.ResponseError.error_string)
}
inline void ResponseError::set_error_string(const char* value, size_t size) {
  set_has_error_string();
  error_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:happy.utils.network.ResponseError.error_string)
}
inline ::std::string* ResponseError::mutable_error_string() {
  set_has_error_string();
  // @@protoc_insertion_point(field_mutable:happy.utils.network.ResponseError.error_string)
  return error_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResponseError::release_error_string() {
  // @@protoc_insertion_point(field_release:happy.utils.network.ResponseError.error_string)
  clear_has_error_string();
  return error_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResponseError::set_allocated_error_string(::std::string* error_string) {
  if (error_string != NULL) {
    set_has_error_string();
  } else {
    clear_has_error_string();
  }
  error_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_string);
  // @@protoc_insertion_point(field_set_allocated:happy.utils.network.ResponseError.error_string)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace network
}  // namespace utils
}  // namespace happy

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_response_5ferror_2eproto__INCLUDED
