// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response_error.proto

#ifndef PROTOBUF_INCLUDED_response_5ferror_2eproto
#define PROTOBUF_INCLUDED_response_5ferror_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_response_5ferror_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_response_5ferror_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_response_5ferror_2eproto();
namespace happy {
namespace utils {
namespace network {
class ResponseError;
class ResponseErrorDefaultTypeInternal;
extern ResponseErrorDefaultTypeInternal _ResponseError_default_instance_;
}  // namespace network
}  // namespace utils
}  // namespace happy
namespace google {
namespace protobuf {
template<> ::happy::utils::network::ResponseError* Arena::CreateMaybeMessage<::happy::utils::network::ResponseError>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace happy {
namespace utils {
namespace network {

// ===================================================================

class ResponseError :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:happy.utils.network.ResponseError) */ {
 public:
  ResponseError();
  virtual ~ResponseError();

  ResponseError(const ResponseError& from);

  inline ResponseError& operator=(const ResponseError& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResponseError(ResponseError&& from) noexcept
    : ResponseError() {
    *this = ::std::move(from);
  }

  inline ResponseError& operator=(ResponseError&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ResponseError& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResponseError* internal_default_instance() {
    return reinterpret_cast<const ResponseError*>(
               &_ResponseError_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ResponseError* other);
  friend void swap(ResponseError& a, ResponseError& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResponseError* New() const final {
    return CreateMaybeMessage<ResponseError>(nullptr);
  }

  ResponseError* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResponseError>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResponseError& from);
  void MergeFrom(const ResponseError& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResponseError* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string error_string = 2;
  bool has_error_string() const;
  void clear_error_string();
  static const int kErrorStringFieldNumber = 2;
  const ::std::string& error_string() const;
  void set_error_string(const ::std::string& value);
  #if LANG_CXX11
  void set_error_string(::std::string&& value);
  #endif
  void set_error_string(const char* value);
  void set_error_string(const char* value, size_t size);
  ::std::string* mutable_error_string();
  ::std::string* release_error_string();
  void set_allocated_error_string(::std::string* error_string);

  // required int32 error_code = 1;
  bool has_error_code() const;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:happy.utils.network.ResponseError)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr error_string_;
  ::google::protobuf::int32 error_code_;
  friend struct ::TableStruct_response_5ferror_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResponseError

// required int32 error_code = 1;
inline bool ResponseError::has_error_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseError::clear_error_code() {
  error_code_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 ResponseError::error_code() const {
  // @@protoc_insertion_point(field_get:happy.utils.network.ResponseError.error_code)
  return error_code_;
}
inline void ResponseError::set_error_code(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  error_code_ = value;
  // @@protoc_insertion_point(field_set:happy.utils.network.ResponseError.error_code)
}

// required string error_string = 2;
inline bool ResponseError::has_error_string() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseError::clear_error_string() {
  error_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& ResponseError::error_string() const {
  // @@protoc_insertion_point(field_get:happy.utils.network.ResponseError.error_string)
  return error_string_.GetNoArena();
}
inline void ResponseError::set_error_string(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  error_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:happy.utils.network.ResponseError.error_string)
}
#if LANG_CXX11
inline void ResponseError::set_error_string(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  error_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:happy.utils.network.ResponseError.error_string)
}
#endif
inline void ResponseError::set_error_string(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  error_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:happy.utils.network.ResponseError.error_string)
}
inline void ResponseError::set_error_string(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  error_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:happy.utils.network.ResponseError.error_string)
}
inline ::std::string* ResponseError::mutable_error_string() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:happy.utils.network.ResponseError.error_string)
  return error_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResponseError::release_error_string() {
  // @@protoc_insertion_point(field_release:happy.utils.network.ResponseError.error_string)
  if (!has_error_string()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return error_string_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResponseError::set_allocated_error_string(::std::string* error_string) {
  if (error_string != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  error_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_string);
  // @@protoc_insertion_point(field_set_allocated:happy.utils.network.ResponseError.error_string)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace network
}  // namespace utils
}  // namespace happy

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_response_5ferror_2eproto
